image: bostrot/flutter:latest

build:
  stage: build
  script:
    - pwd
    - chmod +x release-script.sh
    - apt-get update && apt-get install -y zip wget
    - wget https://github.com/cli/cli/releases/download/v2.0.0/gh_2.0.0_linux_amd64.deb
    - dpkg -i gh_2.0.0_linux_amd64.deb
    - echo $GITHUB_TOKEN > token
    - gh auth login --with-token < token
    - ./release-script.sh

    
