name: wsl2distromanager
description: A GUI to quickly manage your WSL instances.

publish_to: 'none'
version: 1.3.4 # Current version

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  localization: ^2.1.0
  desktop_window: ^0.4.0
  fluent_ui: ^3.12.0
  system_theme: ^2.0.0
  file_picker: ^5.0.1
  url_launcher: ^6.0.20
  dio: ^4.0.6
  package_info_plus: ^1.4.2
  plausible_analytics: ^0.2.1
  shared_preferences: ^2.0.13
  shelf_static: ^1.1.0
  shelf: ^1.3.0
  window_manager: ^0.2.5
  provider: ^6.0.3
  flutter_acrylic: ^1.0.0+2
  system_info2: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.5.1
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/i18n/

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
