name: wsl2distromanager
description: A GUI to quickly manage your WSL instances.

publish_to: 'none'
version: 1.2.1 # Current version

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  localization: ^2.1.0
  desktop_window: ^0.4.0
  fluent_ui: ^3.12.0
  system_theme: ^2.0.0
  file_picker: ^4.5.1
  url_launcher: ^6.0.20
  dio: ^4.0.6
  package_info_plus: ^1.4.2
  # bitsdojo_window: ^0.1.1+1
  bitsdojo_window_flutter3:
    git: https://github.com/bostrot/bitsdojo_window_flutter3.git
      
  plausible_analytics: ^0.2.1
  shared_preferences: ^2.0.13
  shelf_static: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.5.1
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/i18n/

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
