name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello there! As you are a first time Issuer please read our [Code of Conduct](https://github.com/bostrot/wsl2-distro-manager/blob/main/CODE_OF_CONDUCT.md). Please also check whether your issue description is reasonable and complete. If you are having an issue always include the version you are using (WSL, this app, Windows) as well as a way to reproduce it. Thank you for reading! Now continue :)"
        pr-message: "Hello there! As you are a first time Contributor please read our [Code of Conduct](https://github.com/bostrot/wsl2-distro-manager/blob/main/CODE_OF_CONDUCT.md) as well our [Contribution Guideline](https://github.com/bostrot/wsl2-distro-manager/blob/main/CONTRIBUTING.md). At least the latter is short, I promise! Thank you! Now continue :)"
