name: Publish to WinGet
on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      ref_name:
        description: "Reference (branch or tag) to use"
        default: $(git describe --tags $(git rev-list --tags --max-count=1))

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: Bostrot.WSLManager
          version: ${{ github.event.release.tag_name || github.ref_name }}.0
          installers-regex: '\.msix$' # Only .exe files
          token: ${{ secrets.WINGET_TOKEN }}
