name: Publish to WinGet
on:
  release:
    types: [released]
  workflow_dispatch:
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: Bostrot.WSLManager
          version: ${{ github.event.release.tag_name || github.ref_name }}.0
          installers-regex: '\.msix$' # Only .exe files
          token: ${{ secrets.WINGET_TOKEN }}
